volumes:
  node_modules:

services:
  development:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.node
      target: builder
    image: resume-2026-development
    working_dir: /app
    volumes:
      - ..:/app:cached
      - node_modules:/app/node_modules
    init: true
    tty: true
    ports:
      - '8000:8000'
    environment:
      NODE_ENV: development
    command: ['npm', 'run', 'develop', '--', '--host', '0.0.0.0']

  devcontainer:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.node
      target: devcontainer
    image: resume-2026-dev
    working_dir: /app
    volumes:
      - ..:/app:cached
      - node_modules:/app/node_modules
    init: true
    tty: true
    environment:
      NODE_ENV: development
