FROM node:24.18.1 AS builder

WORKDIR /app

RUN chown node:node /app

COPY --chown=node:node ./package.json /app/package.json
COPY --chown=node:node ./package-lock.json /app/package-lock.json

USER node

RUN npm i

FROM builder AS devcontainer

USER root

RUN apt-get update && apt-get install -y \
    nano \
    bubblewrap \
    socat \
    zsh \
    curl \
    git \
    && apt-get clean

USER node

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended \
    && sed -i 's/^plugins=(.*/plugins=(git z)/' /home/node/.zshrc
